use std::collections::BTreeSet;
use std::fmt::Write;

use crate::naming;
use crate::spec::{ChampionEntry, NumericEntry, QueueTypeEntry, StringEntry};

const CHAMPION_COUNT_MAX: u32 = 1_024;
const ENTRY_COUNT_MAX: u32 = 4_096;
const OUTPUT_CAPACITY: usize = 256 * 1024;

pub struct ConstsInput<'a> {
    pub champions: &'a [ChampionEntry],
    pub game_modes: &'a [StringEntry],
    pub game_types: &'a [StringEntry],
    pub maps: &'a [NumericEntry<u16>],
    pub queue_types: &'a [QueueTypeEntry],
    pub queues: &'a [NumericEntry<u16>],
    pub seasons: &'a [NumericEntry<u8>],
}

struct ConstPair {
    doc: String,
    name: String,
    value: String,
}

pub fn consts_generate(input: &ConstsInput) -> String {
    assert!(!input.champions.is_empty(), "champions must not be empty");
    assert!(!input.queues.is_empty(), "queues must not be empty");

    let mut output = String::with_capacity(OUTPUT_CAPACITY);

    output.push_str("// Generated by srcgen. Do not edit.\n");
    output.push_str("#![allow(clippy::pedantic)]\n");

    champions_emit(&mut output, input.champions);

    newtype_emit(
        &mut output,
        &NewtypeSpec {
            doc: "A League of Legends map identifier.",
            pairs: &numeric_pairs(input.maps),
            repr: "u16",
            type_name: "Map",
        },
    );

    newtype_emit(
        &mut output,
        &NewtypeSpec {
            doc: "A matchmaking queue identifier.",
            pairs: &numeric_pairs(input.queues),
            repr: "u16",
            type_name: "Queue",
        },
    );

    newtype_emit(
        &mut output,
        &NewtypeSpec {
            doc: "A ranked season identifier.",
            pairs: &numeric_pairs(input.seasons),
            repr: "u8",
            type_name: "Season",
        },
    );

    string_module_emit(
        &mut output,
        &StringModuleSpec {
            doc: "Game-mode string constants.",
            module_name: "game_mode",
            pairs: &string_pairs(input.game_modes),
        },
    );

    string_module_emit(
        &mut output,
        &StringModuleSpec {
            doc: "Game-type string constants.",
            module_name: "game_type",
            pairs: &string_pairs(input.game_types),
        },
    );

    string_module_emit(
        &mut output,
        &StringModuleSpec {
            doc: "Ranked queue-type string constants.",
            module_name: "queue_type",
            pairs: &queue_type_pairs(input.queue_types),
        },
    );

    assert!(
        output.contains("pub struct Queue"),
        "consts output must contain Queue"
    );

    output
}

fn numeric_pairs<T: std::fmt::Display>(entries: &[NumericEntry<T>]) -> Vec<ConstPair> {
    assert!(!entries.is_empty(), "numeric entries must not be empty");
    assert!(
        entries.len() <= ENTRY_COUNT_MAX as usize,
        "entry count exceeds {ENTRY_COUNT_MAX}"
    );

    let mut pairs = Vec::with_capacity(entries.len());

    for entry in entries {
        pairs.push(ConstPair {
            doc: format!("`{}`.", entry.name),
            name: naming::const_name(&entry.name),
            value: entry.value.to_string(),
        });
    }

    pairs
}

fn string_pairs(entries: &[StringEntry]) -> Vec<ConstPair> {
    assert!(!entries.is_empty(), "string entries must not be empty");
    assert!(
        entries.len() <= ENTRY_COUNT_MAX as usize,
        "entry count exceeds {ENTRY_COUNT_MAX}"
    );

    let mut pairs = Vec::with_capacity(entries.len());

    for entry in entries {
        pairs.push(ConstPair {
            doc: format!("`{}`.", entry.value),
            name: naming::const_name(&entry.name),
            value: entry.value.clone(),
        });
    }

    pairs
}

fn queue_type_pairs(entries: &[QueueTypeEntry]) -> Vec<ConstPair> {
    assert!(!entries.is_empty(), "queue type entries must not be empty");
    assert!(
        entries.len() <= ENTRY_COUNT_MAX as usize,
        "entry count exceeds {ENTRY_COUNT_MAX}"
    );

    let mut pairs = Vec::with_capacity(entries.len());

    for entry in entries {
        pairs.push(ConstPair {
            doc: format!("`{}`.", entry.queue_type),
            name: naming::const_name(&entry.name),
            value: entry.queue_type.clone(),
        });
    }

    pairs
}

fn pairs_sorted_unique(pairs: &[ConstPair]) -> Vec<&ConstPair> {
    assert!(
        pairs.len() <= ENTRY_COUNT_MAX as usize,
        "entry count exceeds {ENTRY_COUNT_MAX}"
    );

    let mut names: BTreeSet<&str> = BTreeSet::new();

    for pair in pairs {
        assert!(
            names.insert(&pair.name),
            "duplicate const name: {}",
            pair.name
        );
    }

    let mut sorted: Vec<&ConstPair> = pairs.iter().collect();

    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    sorted
}

struct NewtypeSpec<'a> {
    doc: &'a str,
    pairs: &'a [ConstPair],
    repr: &'a str,
    type_name: &'a str,
}

fn newtype_emit(output: &mut String, spec: &NewtypeSpec) {
    let doc = spec.doc;
    let pairs = spec.pairs;
    let repr = spec.repr;
    let type_name = spec.type_name;

    assert!(!pairs.is_empty(), "pairs must not be empty: {type_name}");
    assert!(
        pairs.len() <= ENTRY_COUNT_MAX as usize,
        "entry count exceeds {ENTRY_COUNT_MAX}"
    );

    let sorted = pairs_sorted_unique(pairs);

    let _ = writeln!(output, "\n/// {doc}");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n");
    let _ = writeln!(output, "pub struct {type_name}(pub {repr});");
    let _ = writeln!(output, "\nimpl {type_name} {{");

    let mut iterations: u32 = 0;

    for pair in &sorted {
        iterations += 1;

        assert!(
            iterations <= ENTRY_COUNT_MAX,
            "entry count exceeds {ENTRY_COUNT_MAX}"
        );

        let _ = writeln!(output, "    /// {}", pair.doc);
        let _ = writeln!(
            output,
            "    pub const {}: {type_name} = {type_name}({});",
            pair.name, pair.value
        );
    }

    output.push_str("\n    /// Every named constant, sorted by name.\n");
    let _ = writeln!(
        output,
        "    pub const ALL: [{type_name}; {}] = [",
        sorted.len()
    );

    let mut all_iterations: u32 = 0;

    for pair in &sorted {
        all_iterations += 1;

        assert!(
            all_iterations <= ENTRY_COUNT_MAX,
            "entry count exceeds {ENTRY_COUNT_MAX}"
        );

        let _ = writeln!(output, "        Self::{},", pair.name);
    }

    output.push_str("    ];\n}\n");

    newtype_traits_emit(output, type_name, repr);
}

fn newtype_traits_emit(output: &mut String, type_name: &str, repr: &str) {
    assert!(!type_name.is_empty(), "type name must not be empty");
    assert!(!repr.is_empty(), "repr must not be empty");

    let _ = writeln!(output, "\nimpl core::fmt::Display for {type_name} {{");
    output.push_str(
        "    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n",
    );
    output.push_str("        core::fmt::Display::fmt(&self.0, formatter)\n    }\n}\n");

    let _ = writeln!(output, "\nimpl core::str::FromStr for {type_name} {{");
    output.push_str("    type Err = core::num::ParseIntError;\n\n");
    output.push_str("    fn from_str(text: &str) -> Result<Self, Self::Err> {\n");
    let _ = writeln!(output, "        Ok({type_name}(text.parse()?))");
    output.push_str("    }\n}\n");

    let _ = writeln!(output, "\nimpl serde::Serialize for {type_name} {{");
    output.push_str("    fn serialize<S: serde::Serializer>(&self, serializer: S)");
    output.push_str(" -> Result<S::Ok, S::Error> {\n");
    output.push_str("        serde::Serialize::serialize(&self.0, serializer)\n    }\n}\n");

    let _ = writeln!(
        output,
        "\nimpl<'de> serde::Deserialize<'de> for {type_name} {{"
    );
    output.push_str("    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D)");
    output.push_str(" -> Result<Self, D::Error> {\n");
    let _ = writeln!(
        output,
        "        <{repr} as serde::Deserialize>::deserialize(deserializer).map({type_name})"
    );
    output.push_str("    }\n}\n");
}

struct StringModuleSpec<'a> {
    doc: &'a str,
    module_name: &'a str,
    pairs: &'a [ConstPair],
}

fn string_module_emit(output: &mut String, spec: &StringModuleSpec) {
    let doc = spec.doc;
    let module_name = spec.module_name;
    let pairs = spec.pairs;

    assert!(!pairs.is_empty(), "pairs must not be empty: {module_name}");
    assert!(
        pairs.len() <= ENTRY_COUNT_MAX as usize,
        "entry count exceeds {ENTRY_COUNT_MAX}"
    );

    let _ = writeln!(output, "\n/// {doc}");
    let _ = writeln!(output, "pub mod {module_name} {{");

    let mut iterations: u32 = 0;

    for pair in pairs_sorted_unique(pairs) {
        iterations += 1;

        assert!(
            iterations <= ENTRY_COUNT_MAX,
            "entry count exceeds {ENTRY_COUNT_MAX}"
        );

        let _ = writeln!(output, "    /// {}", pair.doc);
        let _ = writeln!(
            output,
            "    pub const {}: &str = {:?};",
            pair.name, pair.value
        );
    }

    output.push_str("}\n");
}

fn champions_emit(output: &mut String, champions: &[ChampionEntry]) {
    assert!(!champions.is_empty(), "champions must not be empty");
    assert!(
        champions.len() <= CHAMPION_COUNT_MAX as usize,
        "champion count exceeds {CHAMPION_COUNT_MAX}",
    );

    let mut pairs = Vec::with_capacity(champions.len());

    for champion in champions {
        pairs.push(ConstPair {
            doc: format!("{}.", champion.name),
            name: naming::const_name(&champion.alias),
            value: champion.id.to_string(),
        });
    }

    newtype_emit(
        output,
        &NewtypeSpec {
            doc: "A League of Legends champion identifier.",
            pairs: &pairs,
            repr: "i16",
            type_name: "Champion",
        },
    );

    output.push_str("\n/// Every champion as `(id, alias, display name)`, sorted by id.\n");
    let _ = writeln!(
        output,
        "pub const CHAMPIONS: [(i16, &str, &str); {}] = [",
        champions.len(),
    );

    let mut iterations: u32 = 0;
    let mut id_previous: i16 = i16::MIN;

    for champion in champions {
        iterations += 1;

        assert!(
            iterations <= CHAMPION_COUNT_MAX,
            "champion count exceeds {CHAMPION_COUNT_MAX}"
        );
        assert!(
            champion.id > id_previous,
            "champions must be sorted by id: {}",
            champion.id
        );

        id_previous = champion.id;

        let _ = writeln!(
            output,
            "    ({}, {:?}, {:?}),",
            champion.id, champion.alias, champion.name,
        );
    }

    output.push_str("];\n");
    output.push_str(CHAMPION_NAME_SOURCE);
}

const CHAMPION_NAME_SOURCE: &str = "
/// The display name for a champion, or `None` if the id is unknown.
pub fn champion_name(champion: Champion) -> Option<&'static str> {
    let index = CHAMPIONS.binary_search_by_key(&champion.0, |entry| entry.0).ok()?;

    Some(CHAMPIONS[index].2)
}
";
