use std::fmt::Write;

use crate::generate::docs;
use crate::naming;
use crate::spec::{OpenApi, Operation, Parameter, SchemaObject};

const ARGUMENT_BASE_COUNT: usize = 2;
const ARGUMENT_COUNT_MAX: usize = 8;
const OPERATION_COUNT_MAX: u32 = 256;
const OUTPUT_CAPACITY: usize = 512 * 1024;
const PARAMETER_COUNT_MAX: u32 = 32;
const QUERY_STRUCT_THRESHOLD: usize = 3;
const SCHEMA_PREFIX: &str = "#/components/schemas/";

const BEARER_OPERATION_IDS: [&str; 4] = [
    "account-v1.getByAccessToken",
    "lol-rso-match-v1.getMatch",
    "lol-rso-match-v1.getMatchIds",
    "lol-rso-match-v1.getTimeline",
];

const HEADER_SOURCE: &str = "// Generated by srcgen. Do not edit.
#![allow(clippy::pedantic)]

use std::borrow::Cow;

use crate::client::{Auth, RequestPlan, RiotApi, path_encode};
use crate::error::Error;

use super::routes::{PlatformRoute, RegionalRoute, ValPlatformRoute};
";

struct ArgumentSpec {
    doc: Option<String>,
    ident: String,
    is_string: bool,
    name_original: String,
    type_text: &'static str,
}

struct OperationRecord<'a> {
    method: &'static str,
    operation: &'a Operation,
    path: &'a str,
}

struct MethodPlan<'a> {
    arguments_path: Vec<ArgumentSpec>,
    arguments_query_optional: Vec<ArgumentSpec>,
    arguments_query_required: Vec<ArgumentSpec>,
    body_type: Option<String>,
    description: Option<&'a str>,
    fn_name: String,
    is_bearer: bool,
    method: &'static str,
    nullable_404: bool,
    operation_id: &'a str,
    path_template: String,
    query_struct_lifetime: bool,
    query_struct_name: Option<String>,
    reference_url: Option<&'a str>,
    return_type: String,
    route_type: &'static str,
}

pub fn endpoints_generate(open_api: &OpenApi) -> anyhow::Result<String> {
    let records = operations_collect(open_api);

    assert!(!records.is_empty(), "operations must not be empty");
    assert!(
        records.len() <= OPERATION_COUNT_MAX as usize,
        "operation count exceeds {OPERATION_COUNT_MAX}",
    );

    bearer_ids_verify(&records);

    let mut structs = String::with_capacity(OUTPUT_CAPACITY / 8);
    let mut methods = String::with_capacity(OUTPUT_CAPACITY);
    let mut iterations: u32 = 0;

    for record in &records {
        iterations += 1;

        assert!(
            iterations <= OPERATION_COUNT_MAX,
            "operation count exceeds {OPERATION_COUNT_MAX}"
        );

        let plan = method_plan(record)?;

        query_struct_emit(&mut structs, &plan);
        method_emit(&mut methods, &plan);
    }

    let mut output = String::with_capacity(OUTPUT_CAPACITY);

    output.push_str(HEADER_SOURCE);
    output.push_str(&structs);
    output.push_str("\nimpl RiotApi {\n");
    output.push_str(&methods);
    output.push_str("}\n");

    assert!(
        output.contains("pub async fn"),
        "endpoints output must contain methods"
    );

    Ok(output)
}

fn bearer_ids_verify(records: &[OperationRecord]) {
    let mut iterations: u32 = 0;

    for bearer_id in &BEARER_OPERATION_IDS {
        iterations += 1;

        assert!(
            iterations <= OPERATION_COUNT_MAX,
            "bearer id count exceeds {OPERATION_COUNT_MAX}"
        );
        assert!(
            records
                .iter()
                .any(|record| record.operation.id == *bearer_id),
            "bearer operation id absent from spec: {bearer_id}",
        );
    }
}

fn operations_collect(open_api: &OpenApi) -> Vec<OperationRecord<'_>> {
    assert!(!open_api.paths.is_empty(), "paths must not be empty");

    let mut records = Vec::with_capacity(open_api.paths.len() * 2);
    let mut iterations: u32 = 0;

    for (path, path_item) in &open_api.paths {
        iterations += 1;

        assert!(
            iterations <= OPERATION_COUNT_MAX,
            "path count exceeds {OPERATION_COUNT_MAX}"
        );

        let operations: [(&'static str, Option<&Operation>); 5] = [
            ("DELETE", path_item.delete.as_ref()),
            ("GET", path_item.get.as_ref()),
            ("PATCH", path_item.patch.as_ref()),
            ("POST", path_item.post.as_ref()),
            ("PUT", path_item.put.as_ref()),
        ];

        for (method, operation) in operations {
            let Some(operation) = operation else {
                continue;
            };

            records.push(OperationRecord {
                method,
                operation,
                path,
            });
        }
    }

    records.sort_by(|a, b| a.operation.id.cmp(&b.operation.id));

    records
}

fn method_plan<'a>(record: &OperationRecord<'a>) -> anyhow::Result<MethodPlan<'a>> {
    let operation = record.operation;

    let Some((prefix, local)) = operation.id.split_once('.') else {
        anyhow::bail!("operation id missing prefix: {}", operation.id);
    };

    let module = naming::module_name(prefix);
    let fn_name = format!("{}_{}", module, naming::field_name(local));

    let (parameters_path, parameters_query_required, parameters_query_optional) =
        parameters_partition(operation)?;

    let names_in_path = path_parameter_names(record.path)?;
    let path_template = path_template(record.path, &names_in_path);

    let arguments_path = arguments_path_ordered(record.path, &parameters_path, &names_in_path)?;
    let arguments_query_required = arguments_build(&parameters_query_required)?;
    let arguments_query_optional = arguments_build(&parameters_query_optional)?;

    let (query_struct_name, query_struct_lifetime) =
        query_struct_of(&fn_name, &arguments_query_optional);

    let body_type = match &operation.request_body {
        Some(request_body) => Some(type_of_body(request_body_schema(request_body)?)?),
        None => None,
    };

    let description = operation
        .description
        .as_deref()
        .or(operation.summary.as_deref());
    let reference_url = operation
        .external_docs
        .as_ref()
        .map(|external_docs| external_docs.url.as_str());

    let return_type = type_of_response(operation)?;
    let nullable_404 = operation.nullable_404 && return_type != "()";

    let plan = MethodPlan {
        arguments_path,
        arguments_query_optional,
        arguments_query_required,
        body_type,
        description,
        fn_name,
        is_bearer: BEARER_OPERATION_IDS.contains(&operation.id.as_str()),
        method: record.method,
        nullable_404,
        operation_id: &operation.id,
        path_template,
        query_struct_lifetime,
        query_struct_name,
        reference_url,
        return_type,
        route_type: route_type_of(&operation.route_enum)?,
    };

    argument_count_verify(&plan);

    assert!(!plan.fn_name.is_empty(), "fn name must not be empty");
    assert!(
        !plan.return_type.is_empty(),
        "return type must not be empty"
    );

    Ok(plan)
}

fn query_struct_of(
    fn_name: &str,
    arguments_query_optional: &[ArgumentSpec],
) -> (Option<String>, bool) {
    let query_struct = arguments_query_optional.len() >= QUERY_STRUCT_THRESHOLD;

    if !query_struct {
        return (None, false);
    }

    let name = format!("{}Query", naming::pascal_name(fn_name));
    let lifetime = arguments_query_optional
        .iter()
        .any(|argument| argument.is_string);

    (Some(name), lifetime)
}

fn argument_count_verify(plan: &MethodPlan) {
    let query_arguments = if plan.query_struct_name.is_some() {
        1
    } else {
        plan.arguments_query_optional.len()
    };

    let argument_count = ARGUMENT_BASE_COUNT
        + usize::from(plan.is_bearer)
        + plan.arguments_path.len()
        + plan.arguments_query_required.len()
        + query_arguments
        + usize::from(plan.body_type.is_some());

    assert!(
        argument_count <= ARGUMENT_COUNT_MAX,
        "argument count exceeds {ARGUMENT_COUNT_MAX}: {}",
        plan.operation_id,
    );
}

fn parameters_partition(
    operation: &Operation,
) -> anyhow::Result<(Vec<&Parameter>, Vec<&Parameter>, Vec<&Parameter>)> {
    assert!(
        operation.parameters.len() <= PARAMETER_COUNT_MAX as usize,
        "parameter count exceeds {PARAMETER_COUNT_MAX}: {}",
        operation.id,
    );

    let mut parameters_path = Vec::with_capacity(operation.parameters.len());
    let mut parameters_query_required = Vec::with_capacity(operation.parameters.len());
    let mut parameters_query_optional = Vec::with_capacity(operation.parameters.len());

    for parameter in &operation.parameters {
        match parameter.location.as_str() {
            "path" => parameters_path.push(parameter),
            "query" => {
                if parameter.required {
                    parameters_query_required.push(parameter);
                } else {
                    parameters_query_optional.push(parameter);
                }
            }
            _ => anyhow::bail!("unsupported parameter location: {}", parameter.location),
        }
    }

    Ok((
        parameters_path,
        parameters_query_required,
        parameters_query_optional,
    ))
}

fn arguments_path_ordered(
    path: &str,
    parameters_path: &[&Parameter],
    names_in_path: &[String],
) -> anyhow::Result<Vec<ArgumentSpec>> {
    assert!(
        names_in_path.len() == parameters_path.len(),
        "path parameter mismatch: {path}",
    );

    let mut arguments = Vec::with_capacity(names_in_path.len());

    for name in names_in_path {
        let Some(parameter) = parameters_path
            .iter()
            .find(|parameter| parameter.name == *name)
        else {
            anyhow::bail!("path parameter missing from spec: {name} in {path}");
        };

        arguments.push(argument_build(parameter)?);
    }

    Ok(arguments)
}

fn arguments_build(parameters: &[&Parameter]) -> anyhow::Result<Vec<ArgumentSpec>> {
    assert!(
        parameters.len() <= PARAMETER_COUNT_MAX as usize,
        "parameter count exceeds {PARAMETER_COUNT_MAX}"
    );

    let mut arguments = Vec::with_capacity(parameters.len());

    for parameter in parameters {
        arguments.push(argument_build(parameter)?);
    }

    Ok(arguments)
}

fn argument_build(parameter: &Parameter) -> anyhow::Result<ArgumentSpec> {
    let field_name = naming::field_name(&parameter.name);
    let ident = if naming::is_rust_keyword(&field_name) {
        format!("r#{field_name}")
    } else {
        field_name
    };

    let (type_text, is_string) = type_of_parameter(parameter)?;

    Ok(ArgumentSpec {
        doc: parameter.description.clone(),
        ident,
        is_string,
        name_original: parameter.name.clone(),
        type_text,
    })
}

fn path_parameter_names(path: &str) -> anyhow::Result<Vec<String>> {
    let mut names = Vec::with_capacity(8);
    let mut remainder = path;
    let mut iterations: u32 = 0;

    while let Some(start) = remainder.find('{') {
        iterations += 1;

        assert!(
            iterations <= PARAMETER_COUNT_MAX,
            "path parameter count exceeds {PARAMETER_COUNT_MAX}"
        );

        let Some(end_relative) = remainder[start..].find('}') else {
            anyhow::bail!("unbalanced path template: {path}");
        };

        names.push(remainder[start + 1..start + end_relative].to_string());

        remainder = &remainder[start + end_relative + 1..];
    }

    Ok(names)
}

fn path_template(path: &str, names: &[String]) -> String {
    let mut template = path.to_string();
    let mut iterations: u32 = 0;

    for name in names {
        iterations += 1;

        assert!(
            iterations <= PARAMETER_COUNT_MAX,
            "path parameter count exceeds {PARAMETER_COUNT_MAX}"
        );

        template = template.replace(&format!("{{{name}}}"), "{}");
    }

    template
}

fn query_struct_emit(structs: &mut String, plan: &MethodPlan) {
    let Some(struct_name) = &plan.query_struct_name else {
        return;
    };

    assert!(
        !plan.arguments_query_optional.is_empty(),
        "query struct must have fields"
    );
    assert!(
        plan.arguments_query_optional.len() <= PARAMETER_COUNT_MAX as usize,
        "query argument count exceeds {PARAMETER_COUNT_MAX}"
    );

    let lifetime = if plan.query_struct_lifetime {
        "<'a>"
    } else {
        ""
    };

    let struct_doc = format!("Optional query parameters for `{}`.", plan.fn_name);

    structs.push('\n');

    docs::doc_emit(structs, "", &struct_doc);

    structs.push_str("#[derive(Clone, Copy, Debug, Default)]\n");
    let _ = writeln!(structs, "pub struct {struct_name}{lifetime} {{");

    let mut sorted: Vec<&ArgumentSpec> = plan.arguments_query_optional.iter().collect();

    sorted.sort_by(|a, b| {
        let left = a.ident.strip_prefix("r#").unwrap_or(&a.ident);
        let right = b.ident.strip_prefix("r#").unwrap_or(&b.ident);

        left.cmp(right)
    });

    for argument in sorted {
        let type_text = if argument.is_string {
            "&'a str"
        } else {
            argument.type_text
        };

        let field_fallback = format!("`{}` query parameter.", argument.name_original);

        docs::doc_emit_or(structs, "    ", argument.doc.as_deref(), &field_fallback);

        let _ = writeln!(structs, "    pub {}: Option<{type_text}>,", argument.ident);
    }

    structs.push_str("}\n");
}

fn method_emit(methods: &mut String, plan: &MethodPlan) {
    assert!(!plan.fn_name.is_empty(), "fn name must not be empty");
    assert!(
        !plan.return_type.is_empty(),
        "return type must not be empty"
    );

    method_doc_emit(methods, plan);
    signature_emit(methods, plan);
    asserts_emit(methods, plan);
    path_line_emit(methods, plan);
    query_lines_emit(methods, plan);

    if plan.body_type.is_some() {
        methods.push_str(
            "\n        let body = serde_json::to_string(body).map_err(Error::body_serialize)?;\n",
        );
    }

    let body_expression = if plan.body_type.is_some() {
        "Some(body)"
    } else {
        "None"
    };
    let auth_expression = if plan.is_bearer {
        "Auth::Bearer(access_token.to_string())"
    } else {
        "Auth::ApiKey"
    };

    let _ = writeln!(methods, "\n        let plan = RequestPlan {{");
    let _ = writeln!(methods, "            auth: {auth_expression},");
    let _ = writeln!(methods, "            body: {body_expression},");
    let _ = writeln!(methods, "            endpoint_id: {:?},", plan.operation_id);
    let _ = writeln!(methods, "            method: {:?},", plan.method);
    let _ = writeln!(methods, "            path,");
    let _ = writeln!(methods, "            query: query_pairs,");
    let _ = writeln!(methods, "            route: route.as_str(),");
    let _ = writeln!(methods, "        }};\n");

    if plan.nullable_404 {
        methods.push_str("        self.execute_optional(plan).await\n    }\n");
    } else if plan.return_type == "()" {
        methods.push_str("        self.execute_unit(plan).await\n    }\n");
    } else {
        methods.push_str("        self.execute(plan).await\n    }\n");
    }
}

fn method_doc_emit(methods: &mut String, plan: &MethodPlan) {
    assert!(
        !plan.operation_id.is_empty(),
        "operation id must not be empty"
    );

    let fallback = format!("Calls the `{}` endpoint.", plan.operation_id);

    methods.push('\n');

    docs::doc_emit_or(methods, "    ", plan.description, &fallback);

    methods.push_str("    ///\n    /// # Riot API reference\n    ///\n");

    if let Some(url) = plan.reference_url {
        let _ = writeln!(methods, "    /// Operation `{}`:", plan.operation_id);
        let _ = writeln!(methods, "    /// <{url}>");
    } else {
        let _ = writeln!(methods, "    /// Operation `{}`.", plan.operation_id);
    }
}

fn signature_emit(methods: &mut String, plan: &MethodPlan) {
    assert!(!plan.fn_name.is_empty(), "fn name must not be empty");
    assert!(
        plan.arguments_path.len() <= PARAMETER_COUNT_MAX as usize,
        "path argument count exceeds {PARAMETER_COUNT_MAX}"
    );
    assert!(
        plan.arguments_query_required.len() <= PARAMETER_COUNT_MAX as usize,
        "required query argument count exceeds {PARAMETER_COUNT_MAX}"
    );
    assert!(
        plan.arguments_query_optional.len() <= PARAMETER_COUNT_MAX as usize,
        "optional query argument count exceeds {PARAMETER_COUNT_MAX}"
    );

    let _ = writeln!(methods, "    pub async fn {}(", plan.fn_name);
    methods.push_str("        &self,\n");

    if plan.is_bearer {
        methods.push_str("        access_token: &str,\n");
    }

    let _ = writeln!(methods, "        route: {},", plan.route_type);

    for argument in &plan.arguments_path {
        let _ = writeln!(
            methods,
            "        {}: {},",
            argument.ident, argument.type_text
        );
    }

    for argument in &plan.arguments_query_required {
        let _ = writeln!(
            methods,
            "        {}: {},",
            argument.ident, argument.type_text
        );
    }

    if let Some(struct_name) = &plan.query_struct_name {
        let lifetime = if plan.query_struct_lifetime {
            "<'_>"
        } else {
            ""
        };

        let _ = writeln!(methods, "        query: &{struct_name}{lifetime},");
    } else {
        for argument in &plan.arguments_query_optional {
            let _ = writeln!(
                methods,
                "        {}: Option<{}>,",
                argument.ident, argument.type_text,
            );
        }
    }

    if let Some(body_type) = &plan.body_type {
        let _ = writeln!(methods, "        body: &{body_type},");
    }

    let return_type = if plan.nullable_404 {
        format!("Option<{}>", plan.return_type)
    } else {
        plan.return_type.clone()
    };

    let _ = writeln!(methods, "    ) -> Result<{return_type}, Error> {{");
}

fn asserts_emit(methods: &mut String, plan: &MethodPlan) {
    assert!(
        plan.arguments_path.len() <= PARAMETER_COUNT_MAX as usize,
        "path argument count exceeds {PARAMETER_COUNT_MAX}"
    );

    let mut count: u32 = 0;

    if plan.is_bearer {
        assert_line_emit(methods, "access_token");
        count += 1;
    }

    for argument in &plan.arguments_path {
        if argument.is_string {
            assert_line_emit(methods, &argument.ident);
            count += 1;
        }
    }

    for argument in &plan.arguments_query_required {
        if argument.is_string {
            assert_line_emit(methods, &argument.ident);
            count += 1;
        }
    }

    let argument_count = 1 + plan.arguments_path.len() + plan.arguments_query_required.len();

    assert!(
        count as usize <= argument_count,
        "emitted more asserts than arguments"
    );

    if count > 0 {
        methods.push('\n');
    }
}

fn assert_line_emit(methods: &mut String, ident: &str) {
    assert!(!ident.is_empty(), "assert ident must not be empty");
    assert!(
        ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
        "assert ident must be a rust identifier: {ident}"
    );

    let phrase = ident.replace('_', " ");

    let _ = writeln!(
        methods,
        "        assert!(!{ident}.is_empty(), {message:?});",
        message = format!("{phrase} must not be empty"),
    );
}

fn path_line_emit(methods: &mut String, plan: &MethodPlan) {
    let template = &plan.path_template;

    if plan.arguments_path.is_empty() {
        let _ = writeln!(methods, "        let path = Cow::Borrowed({template:?});");

        return;
    }

    let mut format_arguments = Vec::with_capacity(plan.arguments_path.len());

    for argument in &plan.arguments_path {
        if argument.is_string {
            format_arguments.push(format!("path_encode({})", argument.ident));
        } else {
            format_arguments.push(argument.ident.clone());
        }
    }

    let _ = writeln!(
        methods,
        "        let path = Cow::Owned(format!({template:?}, {}));",
        format_arguments.join(", "),
    );
}

fn query_lines_emit(methods: &mut String, plan: &MethodPlan) {
    assert!(
        plan.arguments_query_required.len() <= PARAMETER_COUNT_MAX as usize,
        "required query argument count exceeds {PARAMETER_COUNT_MAX}"
    );
    assert!(
        plan.arguments_query_optional.len() <= PARAMETER_COUNT_MAX as usize,
        "optional query argument count exceeds {PARAMETER_COUNT_MAX}"
    );

    let required = &plan.arguments_query_required;
    let optional = &plan.arguments_query_optional;

    if required.is_empty() && optional.is_empty() {
        methods.push_str("        let query_pairs: Vec<(&'static str, String)> = Vec::new();\n");

        return;
    }

    let mutable = if optional.is_empty() { "" } else { "mut " };

    if required.is_empty() {
        let _ = write!(
            methods,
            "\n        let {mutable}query_pairs: Vec<(&'static str,"
        );
        let _ = writeln!(
            methods,
            " String)> = Vec::with_capacity({});",
            optional.len()
        );
    } else {
        let mut pairs = Vec::with_capacity(required.len());

        for argument in required {
            pairs.push(format!(
                "({:?}, {}.to_string())",
                argument.name_original, argument.ident,
            ));
        }

        let _ = writeln!(
            methods,
            "\n        let {mutable}query_pairs: Vec<(&'static str, String)> = vec![{}];",
            pairs.join(", "),
        );
    }

    let access_prefix = if plan.query_struct_name.is_some() {
        "query."
    } else {
        ""
    };

    for argument in optional {
        let _ = writeln!(
            methods,
            "\n        if let Some(value) = {access_prefix}{} {{",
            argument.ident,
        );
        let _ = writeln!(
            methods,
            "            query_pairs.push(({:?}, value.to_string()));",
            argument.name_original,
        );
        let _ = writeln!(methods, "        }}");
    }
}

fn type_of_parameter(parameter: &Parameter) -> anyhow::Result<(&'static str, bool)> {
    let type_name = parameter.schema.type_name.as_deref();
    let format = parameter.schema.format.as_deref();

    match (type_name, format) {
        (Some("integer"), Some("int32")) => Ok(("i32", false)),
        (Some("integer"), Some("int64")) => Ok(("i64", false)),
        (Some("string"), None) => Ok(("&str", true)),
        _ => anyhow::bail!(
            "unsupported parameter type for {}: {type_name:?} {format:?}",
            parameter.name
        ),
    }
}

fn request_body_schema(request_body: &crate::spec::RequestBody) -> anyhow::Result<&SchemaObject> {
    let Some(media) = request_body.content.get("application/json") else {
        anyhow::bail!("request body missing application/json content");
    };

    Ok(&media.schema)
}

fn type_of_body(schema: &SchemaObject) -> anyhow::Result<String> {
    let Some(reference) = &schema.reference else {
        anyhow::bail!("request body schema must be a reference");
    };

    qualified_reference(reference)
}

fn type_of_response(operation: &Operation) -> anyhow::Result<String> {
    let Some(response) = operation.responses.get("200") else {
        return Ok("()".to_string());
    };

    let Some(content) = &response.content else {
        return Ok("()".to_string());
    };

    let Some(media) = content.get("application/json") else {
        anyhow::bail!(
            "response missing application/json content: {}",
            operation.id
        );
    };

    response_type_text(&media.schema, &operation.id)
}

fn response_type_text(schema: &SchemaObject, operation_id: &str) -> anyhow::Result<String> {
    if let Some(reference) = &schema.reference {
        return qualified_reference(reference);
    }

    match schema.type_name.as_deref() {
        Some("array") => {
            let Some(items) = &schema.items else {
                anyhow::bail!("response array missing items: {operation_id}");
            };

            if let Some(reference) = &items.reference {
                return Ok(format!("Vec<{}>", qualified_reference(reference)?));
            }

            Ok(format!("Vec<{}>", scalar_owned(items, operation_id)?))
        }
        Some("object") => {
            let Some(value_schema) = &schema.additional_properties else {
                anyhow::bail!("response object missing additionalProperties: {operation_id}");
            };

            if let Some(inner) = &value_schema.additional_properties {
                assert!(
                    inner.reference.is_none(),
                    "nested response map must be scalar: {operation_id}"
                );

                return Ok(format!(
                    "rustc_hash::FxHashMap<String, rustc_hash::FxHashMap<String, {}>>",
                    scalar_owned(inner, operation_id)?,
                ));
            }

            assert!(
                value_schema.reference.is_none(),
                "response map of references is unsupported: {operation_id}",
            );

            Ok(format!(
                "rustc_hash::FxHashMap<String, {}>",
                scalar_owned(value_schema, operation_id)?
            ))
        }
        Some(_) => Ok(scalar_owned(schema, operation_id)?.to_string()),
        None => anyhow::bail!("response schema missing type: {operation_id}"),
    }
}

fn scalar_owned(schema: &SchemaObject, operation_id: &str) -> anyhow::Result<&'static str> {
    let type_name = schema.type_name.as_deref();
    let format = schema.format.as_deref();

    match (type_name, format) {
        (Some("boolean"), None) => Ok("bool"),
        (Some("integer"), Some("int32")) => Ok("i32"),
        (Some("integer"), Some("int64")) => Ok("i64"),
        (Some("number"), Some("double")) => Ok("f64"),
        (Some("number"), Some("float")) => Ok("f32"),
        (Some("string"), None) => Ok("String"),
        _ => anyhow::bail!("unsupported scalar for {operation_id}: {type_name:?} {format:?}"),
    }
}

fn qualified_reference(reference: &str) -> anyhow::Result<String> {
    assert!(
        reference.starts_with(SCHEMA_PREFIX),
        "unexpected reference shape: {reference}"
    );

    let schema_name = &reference[SCHEMA_PREFIX.len()..];

    let Some((prefix, raw_name)) = schema_name.split_once('.') else {
        anyhow::bail!("reference missing prefix: {reference}");
    };

    let module = naming::module_name(prefix);
    let struct_name = naming::struct_name(raw_name);

    assert!(
        !struct_name.is_empty(),
        "struct name must not be empty: {reference}"
    );

    Ok(format!("super::models::{module}::{struct_name}"))
}

fn route_type_of(route_enum: &str) -> anyhow::Result<&'static str> {
    assert!(!route_enum.is_empty(), "route enum must not be empty");

    match route_enum {
        "platform" => Ok("PlatformRoute"),
        "regional" => Ok("RegionalRoute"),
        "val-platform" => Ok("ValPlatformRoute"),
        _ => anyhow::bail!("unknown route enum: {route_enum}"),
    }
}
