use std::collections::BTreeSet;
use std::fmt::Write;

use crate::spec::{OpenApi, Operation};

const OPERATION_COUNT_MAX: u32 = 256;
const OUTPUT_CAPACITY: usize = 32 * 1024;

const ENDPOINT_SOURCE: &str = "
/// Static description of one generated endpoint.
#[derive(Clone, Copy, Debug)]
pub struct Endpoint {
    /// The Riot operation id, e.g. `\"summoner-v4.getByPUUID\"`.
    pub id: &'static str,
    /// The HTTP method, e.g. `\"GET\"`.
    pub method: &'static str,
    /// The templated request path.
    pub path: &'static str,
    /// Which routing-value family the endpoint expects.
    pub route_kind: RouteKind,
}
";

struct EndpointRecord {
    id: String,
    method: &'static str,
    path: String,
    route_kind: &'static str,
}

pub fn meta_generate(open_api: &OpenApi) -> anyhow::Result<String> {
    let endpoints = endpoints_collect(open_api)?;

    assert!(!endpoints.is_empty(), "endpoints must not be empty");
    assert!(
        endpoints.len() <= OPERATION_COUNT_MAX as usize,
        "endpoint count exceeds {OPERATION_COUNT_MAX}",
    );

    let mut output = String::with_capacity(OUTPUT_CAPACITY);

    output.push_str("// Generated by srcgen. Do not edit.\n");
    output.push_str("#![allow(clippy::pedantic)]\n");
    output.push_str("\nuse super::routes::RouteKind;\n");
    output.push_str(ENDPOINT_SOURCE);
    output.push_str("\n/// Every generated endpoint, sorted by operation id.\n");

    let _ = writeln!(
        output,
        "pub const ENDPOINTS: [Endpoint; {}] = [",
        endpoints.len()
    );

    let mut iterations: u32 = 0;

    for endpoint in &endpoints {
        iterations += 1;

        assert!(
            iterations <= OPERATION_COUNT_MAX,
            "endpoint count exceeds {OPERATION_COUNT_MAX}"
        );

        let _ = writeln!(output, "    Endpoint {{");
        let _ = writeln!(output, "        id: {:?},", endpoint.id);
        let _ = writeln!(output, "        method: {:?},", endpoint.method);
        let _ = writeln!(output, "        path: {:?},", endpoint.path);
        let _ = writeln!(output, "        route_kind: {},", endpoint.route_kind);
        let _ = writeln!(output, "    }},");
    }

    output.push_str("];\n");

    Ok(output)
}

fn endpoints_collect(open_api: &OpenApi) -> anyhow::Result<Vec<EndpointRecord>> {
    assert!(!open_api.paths.is_empty(), "paths must not be empty");

    let mut endpoints = Vec::with_capacity(open_api.paths.len() * 2);
    let mut identifiers: BTreeSet<String> = BTreeSet::new();
    let mut iterations: u32 = 0;

    for (path, path_item) in &open_api.paths {
        iterations += 1;

        assert!(
            iterations <= OPERATION_COUNT_MAX,
            "path count exceeds {OPERATION_COUNT_MAX}"
        );

        let operations: [(&'static str, Option<&Operation>); 5] = [
            ("DELETE", path_item.delete.as_ref()),
            ("GET", path_item.get.as_ref()),
            ("PATCH", path_item.patch.as_ref()),
            ("POST", path_item.post.as_ref()),
            ("PUT", path_item.put.as_ref()),
        ];

        for (method, operation) in operations {
            let Some(operation) = operation else {
                continue;
            };

            assert!(
                identifiers.insert(operation.id.clone()),
                "duplicate operation id: {}",
                operation.id,
            );

            endpoints.push(EndpointRecord {
                id: operation.id.clone(),
                method,
                path: path.clone(),
                route_kind: route_kind_of(&operation.route_enum)?,
            });
        }
    }

    endpoints.sort_by(|a, b| a.id.cmp(&b.id));

    Ok(endpoints)
}

fn route_kind_of(route_enum: &str) -> anyhow::Result<&'static str> {
    assert!(!route_enum.is_empty(), "route enum must not be empty");

    match route_enum {
        "platform" => Ok("RouteKind::Platform"),
        "regional" => Ok("RouteKind::Regional"),
        "val-platform" => Ok("RouteKind::ValPlatform"),
        _ => anyhow::bail!("unknown route enum: {route_enum}"),
    }
}
