use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt::Write;

use crate::generate::docs;
use crate::naming;
use crate::spec::SchemaObject;

const FIELD_COUNT_MAX: u32 = 512;
const FIELD_DUPLICATE_SUFFIX_MAX: u32 = 8;
const MODULE_COUNT_MAX: u32 = 128;
const OUTPUT_CAPACITY: usize = 1024 * 1024;
const SCHEMA_COUNT_MAX: u32 = 1_024;
const SCHEMA_PREFIX: &str = "#/components/schemas/";

pub fn models_generate(schemas: &BTreeMap<String, SchemaObject>) -> anyhow::Result<String> {
    assert!(!schemas.is_empty(), "schemas must not be empty");
    assert!(
        schemas.len() <= SCHEMA_COUNT_MAX as usize,
        "schema count exceeds {SCHEMA_COUNT_MAX}"
    );

    let modules = modules_group(schemas)?;
    let mut output = String::with_capacity(OUTPUT_CAPACITY);

    output.push_str("// Generated by srcgen. Do not edit.\n");
    output.push_str("#![allow(clippy::pedantic)]\n");

    let mut iterations: u32 = 0;

    for (module_name, structs) in &modules {
        iterations += 1;

        assert!(
            iterations <= MODULE_COUNT_MAX,
            "module count exceeds {MODULE_COUNT_MAX}"
        );

        let group = module_name.replace('_', "-");

        output.push('\n');
        let _ = writeln!(
            output,
            "/// Data-transfer objects for the `{group}` endpoint group."
        );
        let _ = writeln!(output, "pub mod {module_name} {{");

        let mut struct_iterations: u32 = 0;

        for (struct_name, schema) in structs {
            struct_iterations += 1;

            assert!(
                struct_iterations <= SCHEMA_COUNT_MAX,
                "struct count exceeds {SCHEMA_COUNT_MAX}: {module_name}",
            );

            struct_emit(&mut output, module_name, struct_name, schema)?;
        }

        output.push_str("}\n");
    }

    assert!(
        output.contains("pub struct"),
        "models output must contain structs"
    );

    Ok(output)
}

fn modules_group(
    schemas: &BTreeMap<String, SchemaObject>,
) -> anyhow::Result<BTreeMap<String, Vec<(String, &SchemaObject)>>> {
    let mut modules: BTreeMap<String, Vec<(String, &SchemaObject)>> = BTreeMap::new();
    let mut iterations: u32 = 0;

    for (schema_name, schema) in schemas {
        iterations += 1;

        assert!(
            iterations <= SCHEMA_COUNT_MAX,
            "schema count exceeds {SCHEMA_COUNT_MAX}"
        );

        if schema_name == "Error" {
            continue;
        }

        let Some((prefix, raw_name)) = schema_name.split_once('.') else {
            anyhow::bail!("schema name missing prefix: {schema_name}");
        };

        let module_name = naming::module_name(prefix);
        let struct_name = naming::struct_name(raw_name);

        modules
            .entry(module_name)
            .or_default()
            .push((struct_name, schema));
    }

    assert!(!modules.is_empty(), "modules must not be empty");

    Ok(modules)
}

fn struct_emit(
    output: &mut String,
    module_name: &str,
    struct_name: &str,
    schema: &SchemaObject,
) -> anyhow::Result<()> {
    assert!(
        schema.type_name.as_deref() == Some("object"),
        "schema must be object: {struct_name}"
    );

    let Some(properties) = &schema.properties else {
        anyhow::bail!("schema missing properties: {struct_name}");
    };

    assert!(
        properties.len() <= FIELD_COUNT_MAX as usize,
        "field count exceeds {FIELD_COUNT_MAX}: {struct_name}",
    );

    let required: BTreeSet<&str> = schema
        .required
        .iter()
        .flatten()
        .map(String::as_str)
        .collect();
    let mut used_names: BTreeSet<String> = BTreeSet::new();
    let struct_fallback = format!("The `{struct_name}` object.");

    output.push('\n');

    docs::doc_emit_or(
        output,
        "    ",
        schema.description.as_deref(),
        &struct_fallback,
    );

    output
        .push_str("    #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]\n");
    let _ = writeln!(output, "    pub struct {struct_name} {{");

    let mut fields: Vec<(&String, &SchemaObject)> = properties.iter().collect();

    fields.sort_by_key(|(name, _)| naming::field_name(name));

    let mut iterations: u32 = 0;

    for (property_name, property) in fields {
        iterations += 1;

        assert!(
            iterations <= FIELD_COUNT_MAX,
            "field count exceeds {FIELD_COUNT_MAX}"
        );

        let property_required = required.contains(property_name.as_str());

        field_emit(
            output,
            module_name,
            property_name,
            property,
            property_required,
            &mut used_names,
        )?;
    }

    output.push_str("    }\n");

    Ok(())
}

fn field_emit(
    output: &mut String,
    module_name: &str,
    property_name: &str,
    property: &SchemaObject,
    required: bool,
    used_names: &mut BTreeSet<String>,
) -> anyhow::Result<()> {
    assert!(!property_name.is_empty(), "property name must not be empty");

    let field_name = field_name_unique(property_name, used_names)?;
    let ident = if naming::is_rust_keyword(&field_name) {
        format!("r#{field_name}")
    } else {
        field_name.clone()
    };

    let field_fallback = format!("`{property_name}`.");

    docs::doc_emit_or(
        output,
        "        ",
        property.description.as_deref(),
        &field_fallback,
    );

    let mut attributes: Vec<String> = Vec::with_capacity(2);

    if field_name != property_name {
        attributes.push(format!("rename = {property_name:?}"));
    }

    if !required {
        attributes.push("skip_serializing_if = \"Option::is_none\"".to_string());
    }

    if !attributes.is_empty() {
        let _ = writeln!(output, "        #[serde({})]", attributes.join(", "));
    }

    let type_base = type_of_property(module_name, property_name, property)?;
    let type_full = if required {
        type_base
    } else {
        format!("Option<{type_base}>")
    };

    assert!(
        !type_full.is_empty(),
        "field type must not be empty: {property_name}"
    );

    let _ = writeln!(output, "        pub {ident}: {type_full},");

    Ok(())
}

fn field_name_unique(
    property_name: &str,
    used_names: &mut BTreeSet<String>,
) -> anyhow::Result<String> {
    assert!(!property_name.is_empty(), "property name must not be empty");

    let base = naming::field_name(property_name);

    if used_names.insert(base.clone()) {
        return Ok(base);
    }

    let mut suffix: u32 = 2;

    while suffix <= FIELD_DUPLICATE_SUFFIX_MAX {
        let candidate = format!("{base}_{suffix}");

        if used_names.insert(candidate.clone()) {
            return Ok(candidate);
        }

        suffix += 1;
    }

    anyhow::bail!("field name collision limit reached: {property_name}");
}

fn type_of_property(
    module_name: &str,
    property_name: &str,
    property: &SchemaObject,
) -> anyhow::Result<String> {
    if let Some(reference) = &property.reference {
        return type_of_reference(module_name, reference);
    }

    match property.type_name.as_deref() {
        Some("array") => {
            let Some(items) = &property.items else {
                anyhow::bail!("array property missing items: {property_name}");
            };

            Ok(format!(
                "Vec<{}>",
                type_of_item(module_name, property_name, items)?
            ))
        }
        Some("object") => type_of_object(module_name, property_name, property),
        Some(_) => Ok(type_of_scalar(property)?.to_string()),
        None => anyhow::bail!("property missing type: {property_name}"),
    }
}

fn type_of_object(
    module_name: &str,
    property_name: &str,
    property: &SchemaObject,
) -> anyhow::Result<String> {
    assert!(
        property.type_name.as_deref() == Some("object"),
        "property must be object: {property_name}"
    );

    if let Some(value_schema) = &property.additional_properties {
        let value_type = type_of_map_value(module_name, property_name, value_schema)?;

        return Ok(format!("rustc_hash::FxHashMap<String, {value_type}>"));
    }

    assert!(
        property.properties.is_none(),
        "anonymous object with properties is unsupported: {property_name}",
    );

    Ok("serde_json::Value".to_string())
}

fn type_of_map_value(
    module_name: &str,
    property_name: &str,
    schema: &SchemaObject,
) -> anyhow::Result<String> {
    if let Some(reference) = &schema.reference {
        return type_of_reference(module_name, reference);
    }

    if let Some(inner) = &schema.additional_properties {
        assert!(
            inner.reference.is_none(),
            "nested map value must be scalar: {property_name}"
        );
        assert!(
            inner.additional_properties.is_none(),
            "nested map depth exceeds one: {property_name}",
        );

        return Ok(format!(
            "rustc_hash::FxHashMap<String, {}>",
            type_of_scalar(inner)?
        ));
    }

    Ok(type_of_scalar(schema)?.to_string())
}

fn type_of_item(
    module_name: &str,
    property_name: &str,
    items: &SchemaObject,
) -> anyhow::Result<String> {
    if let Some(reference) = &items.reference {
        return type_of_reference(module_name, reference);
    }

    assert!(
        items.additional_properties.is_none(),
        "array of maps is unsupported: {property_name}"
    );
    assert!(
        items.items.is_none(),
        "array of arrays is unsupported: {property_name}"
    );

    Ok(type_of_scalar(items)?.to_string())
}

fn type_of_scalar(schema: &SchemaObject) -> anyhow::Result<&'static str> {
    let type_name = schema.type_name.as_deref();
    let format = schema.format.as_deref();

    match (type_name, format) {
        (Some("boolean"), None) => Ok("bool"),
        (Some("integer"), Some("int32")) => Ok("i32"),
        (Some("integer"), Some("int64")) => Ok("i64"),
        (Some("number"), Some("double")) => Ok("f64"),
        (Some("number"), Some("float")) => Ok("f32"),
        (Some("string"), None) => Ok("String"),
        _ => anyhow::bail!("unsupported scalar: {type_name:?} {format:?}"),
    }
}

fn type_of_reference(module_name: &str, reference: &str) -> anyhow::Result<String> {
    assert!(
        reference.starts_with(SCHEMA_PREFIX),
        "unexpected reference shape: {reference}"
    );

    let schema_name = &reference[SCHEMA_PREFIX.len()..];

    let Some((prefix, raw_name)) = schema_name.split_once('.') else {
        anyhow::bail!("reference missing prefix: {reference}");
    };

    assert!(
        naming::module_name(prefix) == module_name,
        "cross-module reference is unsupported: {reference}",
    );

    Ok(naming::struct_name(raw_name))
}
