use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt::Write;

use crate::naming;
use crate::spec::{RouteEntry, RoutesTable};

const OUTPUT_CAPACITY: usize = 32 * 1024;
const ROUTE_COUNT_MAX: u32 = 64;

const PREAMBLE_SOURCE: &str = "
/// Which family a routing value belongs to.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum RouteKind {
    /// A platform routing value such as `na1`.
    Platform,
    /// A regional routing value such as `americas`.
    Regional,
    /// A Valorant platform routing value such as `na`.
    ValPlatform,
}

/// Error returned when a string does not match a known routing value.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RouteParseError;

impl core::fmt::Display for RouteParseError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(\"unrecognized routing value\")
    }
}

impl std::error::Error for RouteParseError {}
";

pub fn routes_generate(routes_table: &RoutesTable) -> anyhow::Result<String> {
    assert!(
        !routes_table.platform.is_empty(),
        "platform routes must not be empty"
    );
    assert!(
        !routes_table.regional.is_empty(),
        "regional routes must not be empty"
    );

    let mut output = String::with_capacity(OUTPUT_CAPACITY);

    output.push_str("// Generated by srcgen. Do not edit.\n");
    output.push_str("#![allow(clippy::pedantic)]\n");
    output.push_str(PREAMBLE_SOURCE);

    route_enum_emit(
        &mut output,
        &RouteEnumSpec {
            doc: "A platform routing value, one host per game server region.",
            entries: &routes_table.platform,
            regional_include: true,
            type_name: "PlatformRoute",
        },
    )?;

    route_enum_emit(
        &mut output,
        &RouteEnumSpec {
            doc: "A regional routing value, shared by several platforms.",
            entries: &routes_table.regional,
            regional_include: false,
            type_name: "RegionalRoute",
        },
    )?;

    route_enum_emit(
        &mut output,
        &RouteEnumSpec {
            doc: "A Valorant platform routing value.",
            entries: &routes_table.val_platform,
            regional_include: false,
            type_name: "ValPlatformRoute",
        },
    )?;

    assert!(
        output.contains("pub enum PlatformRoute"),
        "routes output must contain PlatformRoute"
    );

    Ok(output)
}

struct RouteEnumSpec<'a> {
    doc: &'a str,
    entries: &'a BTreeMap<String, RouteEntry>,
    regional_include: bool,
    type_name: &'a str,
}

fn route_enum_emit(output: &mut String, spec: &RouteEnumSpec) -> anyhow::Result<()> {
    let doc = spec.doc;
    let entries = spec.entries;
    let regional_include = spec.regional_include;
    let type_name = spec.type_name;

    assert!(
        !entries.is_empty(),
        "entries must not be empty: {type_name}"
    );
    assert!(
        entries.len() <= ROUTE_COUNT_MAX as usize,
        "route count exceeds {ROUTE_COUNT_MAX}"
    );

    let mut identifiers: BTreeSet<u8> = BTreeSet::new();

    let _ = writeln!(output, "\n/// {doc}");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n#[repr(u8)]\n");
    let _ = writeln!(output, "pub enum {type_name} {{");

    let mut iterations: u32 = 0;

    for (key, entry) in entries {
        iterations += 1;

        assert!(
            iterations <= ROUTE_COUNT_MAX,
            "route count exceeds {ROUTE_COUNT_MAX}"
        );
        assert!(
            identifiers.insert(entry.id),
            "duplicate route id: {}",
            entry.id
        );

        let _ = writeln!(output, "    /// The `{key}` routing value.");
        let _ = writeln!(output, "    {} = {},", naming::variant_name(key), entry.id);
    }

    output.push_str("}\n");
    let _ = writeln!(output, "\nimpl {type_name} {{");

    all_array_emit(output, type_name, entries);
    as_str_emit(output, entries);

    if regional_include {
        regional_route_emit(output, entries)?;
    }

    output.push_str("}\n");

    display_impl_emit(output, type_name);
    from_str_impl_emit(output, type_name, entries);
    serde_impl_emit(output, type_name);

    Ok(())
}

fn all_array_emit(output: &mut String, type_name: &str, entries: &BTreeMap<String, RouteEntry>) {
    assert!(!entries.is_empty(), "entries must not be empty");

    let _ = writeln!(output, "    /// Every routing value, in declaration order.");
    let _ = writeln!(
        output,
        "    pub const ALL: [{type_name}; {}] = [",
        entries.len()
    );

    let mut iterations: u32 = 0;

    for key in entries.keys() {
        iterations += 1;

        assert!(
            iterations <= ROUTE_COUNT_MAX,
            "route count exceeds {ROUTE_COUNT_MAX}"
        );

        let _ = writeln!(output, "        Self::{},", naming::variant_name(key));
    }

    output.push_str("    ];\n\n");
}

fn as_str_emit(output: &mut String, entries: &BTreeMap<String, RouteEntry>) {
    assert!(!entries.is_empty(), "entries must not be empty");

    output.push_str("    /// The lowercase token used in the API host, e.g. `\"na1\"`.\n");
    output.push_str("    pub const fn as_str(self) -> &'static str {\n        match self {\n");

    let mut iterations: u32 = 0;

    for key in entries.keys() {
        iterations += 1;

        assert!(
            iterations <= ROUTE_COUNT_MAX,
            "route count exceeds {ROUTE_COUNT_MAX}"
        );

        let _ = writeln!(
            output,
            "            Self::{} => {key:?},",
            naming::variant_name(key)
        );
    }

    output.push_str("        }\n    }\n");
}

fn regional_route_emit(
    output: &mut String,
    entries: &BTreeMap<String, RouteEntry>,
) -> anyhow::Result<()> {
    assert!(!entries.is_empty(), "entries must not be empty");

    output.push_str("\n    /// The regional routing value this platform is served by.\n");
    output.push_str(
        "    pub const fn regional_route(self) -> RegionalRoute {\n        match self {\n",
    );

    let mut iterations: u32 = 0;

    for (key, entry) in entries {
        iterations += 1;

        assert!(
            iterations <= ROUTE_COUNT_MAX,
            "route count exceeds {ROUTE_COUNT_MAX}"
        );

        let Some(regional_route) = &entry.regional_route else {
            anyhow::bail!("platform route missing regional route: {key}");
        };

        let _ = writeln!(
            output,
            "            Self::{} => RegionalRoute::{},",
            naming::variant_name(key),
            naming::variant_name(regional_route),
        );
    }

    output.push_str("        }\n    }\n");

    Ok(())
}

fn display_impl_emit(output: &mut String, type_name: &str) {
    let _ = writeln!(output, "\nimpl core::fmt::Display for {type_name} {{");
    output.push_str(
        "    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n",
    );
    output.push_str("        formatter.write_str(self.as_str())\n    }\n}\n");
}

fn from_str_impl_emit(
    output: &mut String,
    type_name: &str,
    entries: &BTreeMap<String, RouteEntry>,
) {
    assert!(!entries.is_empty(), "entries must not be empty");

    let _ = writeln!(output, "\nimpl core::str::FromStr for {type_name} {{");
    output.push_str("    type Err = RouteParseError;\n\n");
    output.push_str("    fn from_str(text: &str) -> Result<Self, Self::Err> {\n");
    output.push_str("        match text.to_ascii_lowercase().as_str() {\n");

    let mut iterations: u32 = 0;

    for key in entries.keys() {
        iterations += 1;

        assert!(
            iterations <= ROUTE_COUNT_MAX,
            "route count exceeds {ROUTE_COUNT_MAX}"
        );

        let _ = writeln!(
            output,
            "            {key:?} => Ok(Self::{}),",
            naming::variant_name(key)
        );
    }

    output.push_str("            _ => Err(RouteParseError),\n");
    output.push_str("        }\n    }\n}\n");
}

fn serde_impl_emit(output: &mut String, type_name: &str) {
    assert!(!type_name.is_empty(), "type name must not be empty");

    let _ = writeln!(output, "\nimpl serde::Serialize for {type_name} {{");
    output.push_str("    fn serialize<S: serde::Serializer>(&self, serializer: S)");
    output.push_str(" -> Result<S::Ok, S::Error> {\n");
    output.push_str("        serializer.serialize_str(self.as_str())\n    }\n}\n");

    let _ = writeln!(
        output,
        "\nimpl<'de> serde::Deserialize<'de> for {type_name} {{"
    );
    output.push_str("    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D)");
    output.push_str(" -> Result<Self, D::Error> {\n");
    output.push_str(
        "        let text = <String as serde::Deserialize>::deserialize(deserializer)?;\n",
    );
    output.push_str("        text.parse().map_err(serde::de::Error::custom)\n    }\n}\n");
}
